CREATE OR REPLACE PROCEDURE SCOTT.SP_REGISTRO_EMP
(
P_CODIGO IN SCOTT.EMP.EMPNO%TYPE,
P_NOMBRE IN SCOTT.EMP.ENAME%TYPE,
P_SALARIO IN SCOTT.EMP.SAL%TYPE,
P_DEPARTAMENTO IN SCOTT.EMP.DEPTNO%TYPE,
P_PUESTO IN SCOTT.EMP.JOB%TYPE
)
IS
    V_SAL_MAX NUMBER;
    V_SAL_MIN NUMBER;
    V_CONT NUMBER;
    V_DEPTNO NUMBER;
    V_MENS_ERROR VARCHAR2(2000);
    EXCP EXCEPTION;
BEGIN
    -- NO NULOS
    IF (P_CODIGO IS NULL OR P_NOMBRE IS NULL OR P_SALARIO IS NULL OR P_DEPARTAMENTO IS NULL OR P_PUESTO IS NULL) THEN
        V_MENS_ERROR := 'LOS CAMPOS CODIGO, NOMBRE, SALARIO, DEPARTAMENTO Y PUESTO SON OBLIGATORIOS';
        RAISE EXCP;
    END IF;

    -- EN CASO EXISTA CODIGO DE EMPLEADO
    SELECT  COUNT(*)
    INTO    V_CONT
    FROM    SCOTT.EMP
    WHERE   EMPNO = P_CODIGO;
    
    IF (V_CONT > 0) THEN
        V_MENS_ERROR := 'CODIGO YA EXISTE';
        RAISE EXCP;
    END IF;
    
    -- EXISTENCIA EL DEPARTAMENTO
    SELECT  COUNT(*)
    INTO    V_CONT
    FROM    SCOTT.DEPT
    WHERE   DEPTNO = P_DEPARTAMENTO;
    
    IF( V_CONT = 0 ) THEN
      V_MENS_ERROR := 'DEPARTAMENTO NO EXISTE,';
      RAISE EXCP;
    END IF;
    
    -- EXISTENCIA DE DEPARTAMENTO
    SELECT  COUNT(*)
    INTO    V_CONT
    FROM    SCOTT.EMP
    WHERE   DEPTNO = P_DEPARTAMENTO;
    
    V_SAL_MAX := P_SALARIO;
    V_SAL_MIN := P_SALARIO;
    
    IF (V_DEPTNO > 0) THEN
        SELECT  MAX(SAL),   MIN(SAL)
        INTO    V_SAL_MAX,  V_SAL_MIN
        FROM    SCOTT.EMP
        WHERE   DEPTNO = P_DEPARTAMENTO;
    END IF;
         
    IF (P_SALARIO > V_SAL_MAX OR P_SALARIO < V_SAL_MIN) THEN
        V_MENS_ERROR := 'EL SALARIO DEBE ESTAR EN EL RANGO DE: ' || V_SAL_MIN || ' Y ' || V_SAL_MAX;
        RAISE EXCP;
    END IF;
    
    INSERT INTO SCOTT.EMP(EMPNO,ENAME,SAL,DEPTNO,JOB)
    VALUES(P_CODIGO,P_NOMBRE,P_SALARIO,P_DEPARTAMENTO,P_PUESTO);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE('PROCESO CORRECTO');
EXCEPTION
    WHEN EXCP THEN
        DBMS_OUTPUT.PUT_LINE(V_MENS_ERROR);
END;
/


-- TEST NULOS
EXECUTE SCOTT.SP_REGISTRO_EMP(NULL,'    ',NULL,NULL,'   ')

-- TEST CODIGO EXISTENTE
EXECUTE SCOTT.SP_REGISTRO_EMP(7369,'CRISTOPHER',700,20,'BI')


-- TEST SUELDO FUERA DE RANGO
EXECUTE SCOTT.SP_REGISTRO_EMP(7366,'CRISTOPHER',500,20,'BI')



