
-- CONECTANDO CON EL USUARIO FOTO

CONNECT foto/foto

--
-- CREANDO UN PACKAGE CRUD DE LA TABLA "SESION "
--

--
-- CREANDO LA ESPECIFICACIÓN DEL PACKAGE

CREATE OR REPLACE PACKAGE PKG_CRUD_SESION 
AS
	-- CREANDO TYPE RECORD PARA MANIPULAR LAS FILA FACILMENTE
	TYPE PKG_CRUD_SESION_REC IS RECORD (
		ID_USUARIO  SESION.ID_USUARIO%TYPE
		,FORMA_PAGO  SESION.FORMA_PAGO%TYPE
		,ID_SEDE  SESION.ID_SEDE%TYPE
		,FECHA_REGISTRO  SESION.FECHA_REGISTRO%TYPE
		,COMENTARIOS  SESION.COMENTARIOS%TYPE
		,ESTADO  SESION.ESTADO%TYPE
		,MONTO_PAGADO  SESION.MONTO_PAGADO%TYPE
		,ID_SESION  SESION.ID_SESION%TYPE
		,ID_CLIENTE  SESION.ID_CLIENTE%TYPE
		,ID_TEMATICA  SESION.ID_TEMATICA%TYPE
		,ID_PAQUETE  SESION.ID_PAQUETE%TYPE
		,FECHA_HORA_SESION  SESION.FECHA_HORA_SESION%TYPE
		,MONTO_A_PAGAR  SESION.MONTO_A_PAGAR%TYPE
		,ESTADO_PAGO  SESION.ESTADO_PAGO%TYPE
	);
	
	TYPE PKG_CRUD_SESION_TAB IS TABLE OF PKG_CRUD_SESION_REC;

	-- READ ESPECIFICACION
	FUNCTION READ_ (P_ID_SESION IN SESION.ID_SESION%TYPE) RETURN PKG_CRUD_SESION_REC;
	
	-- CREATE ESPECIFICACION
	PROCEDURE CREATE_ (
		P_ID_USUARIO IN SESION.ID_USUARIO%TYPE
		,P_FORMA_PAGO IN SESION.FORMA_PAGO%TYPE DEFAULT NULL 
		,P_ID_SEDE IN SESION.ID_SEDE%TYPE
		,P_FECHA_REGISTRO IN SESION.FECHA_REGISTRO%TYPE DEFAULT NULL 
		,P_COMENTARIOS IN SESION.COMENTARIOS%TYPE DEFAULT NULL 
		,P_ESTADO IN SESION.ESTADO%TYPE DEFAULT NULL 
		,P_MONTO_PAGADO IN SESION.MONTO_PAGADO%TYPE DEFAULT NULL 
		,P_ID_SESION IN SESION.ID_SESION%TYPE
		,P_ID_CLIENTE IN SESION.ID_CLIENTE%TYPE
		,P_ID_TEMATICA IN SESION.ID_TEMATICA%TYPE
		,P_ID_PAQUETE IN SESION.ID_PAQUETE%TYPE
		,P_FECHA_HORA_SESION IN SESION.FECHA_HORA_SESION%TYPE DEFAULT NULL 
		,P_MONTO_A_PAGAR IN SESION.MONTO_A_PAGAR%TYPE DEFAULT NULL 
		,P_ESTADO_PAGO IN SESION.ESTADO_PAGO%TYPE DEFAULT NULL 
	);


	-- UPDATE ESPECIFICACION
	PROCEDURE UPDATE_ (
		P_ID_USUARIO IN SESION.ID_USUARIO%TYPE
		,P_FORMA_PAGO IN SESION.FORMA_PAGO%TYPE DEFAULT NULL 
		,P_ID_SEDE IN SESION.ID_SEDE%TYPE
		,P_FECHA_REGISTRO IN SESION.FECHA_REGISTRO%TYPE DEFAULT NULL 
		,P_COMENTARIOS IN SESION.COMENTARIOS%TYPE DEFAULT NULL 
		,P_ESTADO IN SESION.ESTADO%TYPE DEFAULT NULL 
		,P_MONTO_PAGADO IN SESION.MONTO_PAGADO%TYPE DEFAULT NULL 
		,P_ID_SESION IN SESION.ID_SESION%TYPE
		,P_ID_CLIENTE IN SESION.ID_CLIENTE%TYPE
		,P_ID_TEMATICA IN SESION.ID_TEMATICA%TYPE
		,P_ID_PAQUETE IN SESION.ID_PAQUETE%TYPE
		,P_FECHA_HORA_SESION IN SESION.FECHA_HORA_SESION%TYPE DEFAULT NULL 
		,P_MONTO_A_PAGAR IN SESION.MONTO_A_PAGAR%TYPE DEFAULT NULL 
		,P_ESTADO_PAGO IN SESION.ESTADO_PAGO%TYPE DEFAULT NULL 
	);
	
	-- DELETE ESPECIFICACION
	PROCEDURE DELETE_ (P_ID_SESION IN SESION.ID_SESION%TYPE);
	
END PKG_CRUD_SESION;
/

--
-- CREANDO EL CUERPO DEL PACKAGE

CREATE OR REPLACE PACKAGE BODY PKG_CRUD_SESION 
AS
	-- CREATE_ CUERPO
	PROCEDURE CREATE_ (
		P_ID_USUARIO IN SESION.ID_USUARIO%TYPE
		,P_FORMA_PAGO IN SESION.FORMA_PAGO%TYPE DEFAULT NULL 
		,P_ID_SEDE IN SESION.ID_SEDE%TYPE
		,P_FECHA_REGISTRO IN SESION.FECHA_REGISTRO%TYPE DEFAULT NULL 
		,P_COMENTARIOS IN SESION.COMENTARIOS%TYPE DEFAULT NULL 
		,P_ESTADO IN SESION.ESTADO%TYPE DEFAULT NULL 
		,P_MONTO_PAGADO IN SESION.MONTO_PAGADO%TYPE DEFAULT NULL 
		,P_ID_SESION IN SESION.ID_SESION%TYPE
		,P_ID_CLIENTE IN SESION.ID_CLIENTE%TYPE
		,P_ID_TEMATICA IN SESION.ID_TEMATICA%TYPE
		,P_ID_PAQUETE IN SESION.ID_PAQUETE%TYPE
		,P_FECHA_HORA_SESION IN SESION.FECHA_HORA_SESION%TYPE DEFAULT NULL 
		,P_MONTO_A_PAGAR IN SESION.MONTO_A_PAGAR%TYPE DEFAULT NULL 
		,P_ESTADO_PAGO IN SESION.ESTADO_PAGO%TYPE DEFAULT NULL 
	) IS
	BEGIN
		INSERT INTO SESION(
			ID_USUARIO,FORMA_PAGO,ID_SEDE,FECHA_REGISTRO,COMENTARIOS,ESTADO
			,MONTO_PAGADO,ID_SESION,ID_CLIENTE,ID_TEMATICA,ID_PAQUETE
			,FECHA_HORA_SESION,MONTO_A_PAGAR,ESTADO_PAGO
		) VALUES (
			P_ID_USUARIO,P_FORMA_PAGO,P_ID_SEDE,P_FECHA_REGISTRO,P_COMENTARIOS,P_ESTADO
			,P_MONTO_PAGADO,P_ID_SESION,P_ID_CLIENTE,P_ID_TEMATICA,P_ID_PAQUETE
			,P_FECHA_HORA_SESION,P_MONTO_A_PAGAR,P_ESTADO_PAGO
		);
	END;
	
	-- _READ CUERPO
	FUNCTION READ_ (P_ID_SESION IN SESION.ID_SESION%TYPE) RETURN PKG_CRUD_SESION_REC
	AS
		V_SELECT PKG_CRUD_SESION_REC;
	BEGIN
		SELECT ID_USUARIO ,FORMA_PAGO ,ID_SEDE ,FECHA_REGISTRO
		,COMENTARIOS ,ESTADO ,MONTO_PAGADO ,ID_SESION ,ID_CLIENTE 
		,ID_TEMATICA ,ID_PAQUETE ,FECHA_HORA_SESION ,MONTO_A_PAGAR 
		,ESTADO_PAGO  INTO V_SELECT FROM SESION where ID_SESION = P_ID_SESION;
		RETURN V_SELECT;
	END;
    
	
	-- UPDATE_ CUERPO
	PROCEDURE UPDATE_ (
		P_ID_USUARIO IN SESION.ID_USUARIO%TYPE
		,P_FORMA_PAGO IN SESION.FORMA_PAGO%TYPE DEFAULT NULL 
		,P_ID_SEDE IN SESION.ID_SEDE%TYPE
		,P_FECHA_REGISTRO IN SESION.FECHA_REGISTRO%TYPE DEFAULT NULL 
		,P_COMENTARIOS IN SESION.COMENTARIOS%TYPE DEFAULT NULL 
		,P_ESTADO IN SESION.ESTADO%TYPE DEFAULT NULL 
		,P_MONTO_PAGADO IN SESION.MONTO_PAGADO%TYPE DEFAULT NULL 
		,P_ID_SESION IN SESION.ID_SESION%TYPE
		,P_ID_CLIENTE IN SESION.ID_CLIENTE%TYPE
		,P_ID_TEMATICA IN SESION.ID_TEMATICA%TYPE
		,P_ID_PAQUETE IN SESION.ID_PAQUETE%TYPE
		,P_FECHA_HORA_SESION IN SESION.FECHA_HORA_SESION%TYPE DEFAULT NULL 
		,P_MONTO_A_PAGAR IN SESION.MONTO_A_PAGAR%TYPE DEFAULT NULL 
		,P_ESTADO_PAGO IN SESION.ESTADO_PAGO%TYPE DEFAULT NULL 
	) IS
	BEGIN
		UPDATE SESION SET
			ID_USUARIO = P_ID_USUARIO
			,FORMA_PAGO = P_FORMA_PAGO
			,ID_SEDE = P_ID_SEDE
			,FECHA_REGISTRO = P_FECHA_REGISTRO
			,COMENTARIOS = P_COMENTARIOS
			,ESTADO = P_ESTADO
			,MONTO_PAGADO = P_MONTO_PAGADO
			,ID_CLIENTE = P_ID_CLIENTE
			,ID_TEMATICA = P_ID_TEMATICA
			,ID_PAQUETE = P_ID_PAQUETE
			,FECHA_HORA_SESION = P_FECHA_HORA_SESION
			,MONTO_A_PAGAR = P_MONTO_A_PAGAR
			,ESTADO_PAGO = P_ESTADO_PAGO
		WHERE ID_SESION = P_ID_SESION;
	END;
	
	-- DELETE CUERPO
	PROCEDURE DELETE_ (P_ID_SESION IN SESION.ID_SESION%TYPE) 
	IS
	BEGIN
		DELETE FROM SESION
		WHERE ID_SESION = P_ID_SESION;
	END;
	
END PKG_CRUD_SESION;
