--SON LAS TABLAS Y DATOS QUE CREO QUE SON CONVENIENTES ME AVISAS SI SE MEJORA ALGO 
--------------------------------------------------------
--  DDL for Table SIGDOC_DEPARTAMENTO
--------------------------------------------------------
  CREATE TABLE "SIGDOC_DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL,
	"ES_REGISTRO" CHAR(1 BYTE),
	"USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
   
--------------------------------------------------------
--  DDL for Table SIGDOC_PROVINCIA
--------------------------------------------------------
  CREATE TABLE "SIGDOC_PROVINCIA" 
   (	"ID_PROVINCIA" NUMBER  NOT NULL,
	"ID_DEPARTAMENTO" NUMBER  NOT NULL,   
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL,
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
   
--------------------------------------------------------
--  DDL for Table SIGDOC_DISTRITO
--------------------------------------------------------
  CREATE TABLE "SIGDOC_DISTRITO" 
   (	"ID_DISTRITO" NUMBER  NOT NULL,
	"ID_PROVINCIA" NUMBER  NOT NULL,   
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL,
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
   
--------------------------------------------------------
--  DDL for Table SIGDOC_TIPO_IDENTIFICACION
--------------------------------------------------------
  CREATE TABLE "SIGDOC_TIPO_IDENTIFICACION" 
   (	"ID_TIPO_IDENTIFICACION" NUMBER  NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL , 
	"DESCRIPCION" VARCHAR2(200 BYTE),
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "SIGDOC_TIPO_DOCUMENTO" 
   (	"ID_TIPO_DOCUMENTO" NUMBER  NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL, 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"CODIGO" VARCHAR2(50 BYTE), 
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_TIPO_PROCESO
--------------------------------------------------------

  CREATE TABLE "SIGDOC_TIPO_PROCESO" 
   (	"ID_TIPO_PROCESO" NUMBER  NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL , 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
   
 --------------------------------------------------------
--  DDL for Table SIGDOC_PROCESO
--------------------------------------------------------

  CREATE TABLE "SIGDOC_PROCESO" 
   (	"ID_PROCESO" NUMBER  NOT NULL, 
	"ID_TIPO_PROCESO" NUMBER  NOT NULL,
	"ID_UNIDAD" NUMBER, 
	"ID_ASISTENTE" NUMBER , 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL, 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"TIEMPO_ATENCION" NUMBER,  
	"ES_REGISTRO" CHAR(1 BYTE), 
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_CLIENTE
--------------------------------------------------------

  CREATE TABLE "SIGDOC_CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_TIPO_IDENTIFICACION" NUMBER  NOT NULL, 
	"NRO_IDENTIFICACION" VARCHAR2(20 BYTE)  NOT NULL, 
	"RAZON_SOCIAL" VARCHAR2(100 BYTE)  NOT NULL, 
	"DIRECCION" VARCHAR2(400 BYTE), 
	"UBIGEO" NUMBER  NOT NULL,  
	"TELEFONO" VARCHAR2(50 BYTE), 
	"NOMBRES" VARCHAR2(200 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(200 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(200 BYTE), 
	"CELULAR" VARCHAR2(50 BYTE),
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
    );

--------------------------------------------------------
--  DDL for Table SIGDOC_UNIDAD
--------------------------------------------------------

  CREATE TABLE "SIGDOC_UNIDAD" 
   (	"ID_UNIDAD" NUMBER  NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL , 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_USUARIO
--------------------------------------------------------

  CREATE TABLE "SIGDOC_USUARIO" 
   (	"ID_USUARIO" NUMBER  NOT NULL, 
	"ID_CLIENTE" NUMBER,
	"ID_UNIDAD" NUMBER  NOT NULL,
	"CORREO" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(20 BYTE)  NOT NULL, 
	"CLAVE" VARCHAR2(50 BYTE),  
	"ES_REGISTRO" VARCHAR2(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE 
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_ETAPA
--------------------------------------------------------

  CREATE TABLE "SIGDOC_ETAPA" 
   (	"ID_ETAPA" NUMBER  NOT NULL, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL,
	"DESCRIPCION" VARCHAR2(200 BYTE),
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_ACCION
--------------------------------------------------------

  CREATE TABLE "SIGDOC_ACCION" 
   (	"ID_ACCION" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE)  NOT NULL,
	"DESCRIPCION" VARCHAR2(200 BYTE)  NOT NULL,
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
--------------------------------------------------------
--  DDL for Table SIGDOC_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "SIGDOC_DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER  NOT NULL, 
	"TIPO_DOCUMENTO" NUMBER  NOT NULL,
	"ID_EXPEDIENTE" NUMBER  NOT NULL, 
	"NUMERACION" VARCHAR2(50 BYTE)  NOT NULL,
	"EXTENSION_DOCUMENTO" VARCHAR2(50 BYTE) NOT NULL,
	"ASUNTO" VARCHAR2(500 BYTE), 
	"OBSERVACION" VARCHAR2(4000 BYTE), 
	"ES_VERSIONADO" CHAR(1 BYTE) DEFAULT 'N', 
	"NUMERO_VERSIONADO" NUMBER DEFAULT 0,
	"ES_PRINCIPAL" CHAR(1 BYTE)  NOT NULL,  
	"PROPIETARIO" NUMBER, --USUARIO CREACION
	"FIRMANTE" NUMBER, --USUARIO 
	"RUTA_ARCHIVO" VARCHAR2(400 BYTE), 
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_EXPEDIENTE
--------------------------------------------------------

  CREATE TABLE "SIGDOC_EXPEDIENTE" 
   (	"ID_EXPEDIENTE" NUMBER  NOT NULL, 
	"ID_USUARIO" NUMBER  NOT NULL, 
	"ID_CLIENTE" NUMBER, 
	"ID_PROCESO" NUMBER  NOT NULL, 
	"NRO_EXPEDIENTE" VARCHAR2(100 BYTE)  NOT NULL, 
	"DESCRIPCION" VARCHAR2(2000 BYTE), 
	"ASUNTO" VARCHAR2(500 BYTE), 
	"OBSERVACION" VARCHAR2(4000 BYTE),
	"ES_REGISTRO" CHAR(1 BYTE), 
	"USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_TRAZABILIDAD_EXPEDIENTE
--------------------------------------------------------
CREATE TABLE "SIGDOC_TRAZABILIDAD_EXPEDIENTE" 
   (	"ID_TRAZABILIDAD_EXPEDIENTE" NUMBER  NOT NULL, 
	"REMITENTE" NUMBER  NOT NULL, 
	"DESTINATARIO" NUMBER  NOT NULL, 
	"ID_EXPEDIENTE" NUMBER  NOT NULL, 
	"ID_ACCION" NUMBER NOT NULL, 
	"ID_ETAPA" NUMBER  NOT NULL, 
	"OBSERVACION" LONG , 
	"FECHA_ENVIO" DATE, 
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );

--------------------------------------------------------
--  DDL for Table SIGDOC_NUMERACION
--------------------------------------------------------

  CREATE TABLE "SIGDOC_NUMERACION" 
   (	"ID_UNIDAD" NUMBER  NOT NULL, 
	"ID_TIPO_DOCUMENTO" NUMBER  NOT NULL, 
	"NUMERO_ACTUAL" NUMBER, 
	"FORMATO" VARCHAR2(50 BYTE),
	"ES_REGISTRO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
	"USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
   );
   