--SON LAS TABLAS Y DATOS QUE CREO QUE SON CONVENIENTES ME AVISAS SI SE MEJORA ALGO 
--------------------------------------------------------
--  DML for Table SIGDOC_DEPARTAMENTO
--------------------------------------------------------
 ALTER TABLE SIGDOC.SIGDOC_DEPARTAMENTO ADD CONSTRAINT PK_ID_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO); 
   
--------------------------------------------------------
--  DML for Table SIGDOC_PROVINCIA
-------------------------------------------------------- 
ALTER TABLE SIGDOC.SIGDOC_PROVINCIA ADD CONSTRAINT PK_ID_PROVINCIA PRIMARY KEY (ID_PROVINCIA);

ALTER TABLE SIGDOC.SIGDOC_PROVINCIA ADD CONSTRAINT FK_ID_DEPARTAMENTO_T_PROVINCIA FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES SIGDOC.SIGDOC_DEPARTAMENTO;

--------------------------------------------------------
--  DML for Table SIGDOC_DISTRITO
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_DISTRITO ADD CONSTRAINT PK_ID_DISTRITO PRIMARY KEY (ID_DISTRITO);

ALTER TABLE SIGDOC.SIGDOC_DISTRITO ADD CONSTRAINT FK_ID_PROVINCIA_T_DISTRITO FOREIGN KEY (ID_PROVINCIA) REFERENCES SIGDOC.SIGDOC_PROVINCIA;

--------------------------------------------------------
--  DML for Table SIGDOC_TIPO_IDENTIFICACION
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_TIPO_IDENTIFICACION ADD CONSTRAINT PK_ID_TIPO_IDENTIFICACION PRIMARY KEY (ID_TIPO_IDENTIFICACION);

--------------------------------------------------------
--  DML for Table SIGDOC_TIPO_DOCUMENTO
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_TIPO_DOCUMENTO ADD CONSTRAINT PK_ID_TIPO_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO);

--------------------------------------------------------
--  DML for Table SIGDOC_UNIDAD
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_UNIDAD ADD CONSTRAINT PK_SIGDOC_UNIDAD PRIMARY KEY (ID_UNIDAD);

--------------------------------------------------------
--  DML for Table SIGDOC_CLIENTE
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_CLIENTE ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE);
ALTER TABLE SIGDOC.SIGDOC_CLIENTE ADD CONSTRAINT FK_ID_TIPO_IDENT_T_CLIENTE FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES SIGDOC.SIGDOC_TIPO_IDENTIFICACION;
ALTER TABLE SIGDOC.SIGDOC_CLIENTE ADD CONSTRAINT FK_ID_UBIGEO_T_CLIENTE FOREIGN KEY (UBIGEO) REFERENCES SIGDOC.SIGDOC_DISTRITO;

--------------------------------------------------------
--  DML for Table SIGDOC_USUARIO
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_USUARIO ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO);
ALTER TABLE SIGDOC.SIGDOC_USUARIO  ADD CONSTRAINT FK_ID_CLIENTE__T_USUARIO FOREIGN KEY (ID_CLIENTE) REFERENCES SIGDOC.SIGDOC_CLIENTE;
ALTER TABLE SIGDOC.SIGDOC_USUARIO  ADD CONSTRAINT FK_ID_UNIDAD_T_USUARIO FOREIGN KEY (ID_UNIDAD) REFERENCES SIGDOC.SIGDOC_UNIDAD;


--------------------------------------------------------
--  DML for Table SIGDOC_TIPO_PROCESO
--------------------------------------------------------

    ALTER TABLE SIGDOC.SIGDOC_TIPO_PROCESO ADD CONSTRAINT PK_ID_TIPO_PROCESO PRIMARY KEY (ID_TIPO_PROCESO);
 --------------------------------------------------------
--  DML for Table SIGDOC_PROCESO
-------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_PROCESO ADD CONSTRAINT PK_ID_PROCESO PRIMARY KEY (ID_PROCESO);
ALTER TABLE SIGDOC.SIGDOC_PROCESO ADD CONSTRAINT FK_ID_UNIDAD_T_PROCESO FOREIGN KEY (ID_UNIDAD) REFERENCES SIGDOC.SIGDOC_UNIDAD;
ALTER TABLE SIGDOC.SIGDOC_PROCESO ADD CONSTRAINT FK_ID_ASISTENTE_T_PROCESO FOREIGN KEY (ID_ASISTENTE) REFERENCES SIGDOC.SIGDOC_USUARIO;
ALTER TABLE SIGDOC.SIGDOC_PROCESO ADD CONSTRAINT FK_TIPO_PROCESO_T_PROCESO FOREIGN KEY (ID_TIPO_PROCESO) REFERENCES SIGDOC.SIGDOC_TIPO_PROCESO;
--------------------------------------------------------
--  DML for Table SIGDOC_ETAPA
--------------------------------------------------------

ALTER TABLE SIGDOC.SIGDOC_ETAPA ADD CONSTRAINT PK_ID_ETAPA PRIMARY KEY (ID_ETAPA);   

--------------------------------------------------------
--  DML for Table SIGDOC_ACCION
--------------------------------------------------------

   ALTER TABLE SIGDOC.SIGDOC_ACCION ADD CONSTRAINT PK_ID_ACCION PRIMARY KEY (ID_ACCION); 

--------------------------------------------------------
--  DML for Table SIGDOC_EXPEDIENTE
--------------------------------------------------------

   ALTER TABLE SIGDOC.SIGDOC_EXPEDIENTE ADD CONSTRAINT PK_ID_EXPEDIENTE PRIMARY KEY (ID_EXPEDIENTE);     
   ALTER TABLE SIGDOC.SIGDOC_EXPEDIENTE ADD CONSTRAINT FK_ID_USUARIO_T_EXP FOREIGN KEY (ID_CLIENTE) REFERENCES SIGDOC.SIGDOC_CLIENTE;
   ALTER TABLE SIGDOC.SIGDOC_EXPEDIENTE ADD CONSTRAINT FK_ID_PROCESO_T_EXP FOREIGN KEY (ID_PROCESO) REFERENCES SIGDOC.SIGDOC_PROCESO;  

--------------------------------------------------------
--  DML for Table SIGDOC_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE SIGDOC.SIGDOC_DOCUMENTO ADD CONSTRAINT PK_ID_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO);   
  ALTER TABLE SIGDOC.SIGDOC_DOCUMENTO ADD CONSTRAINT FK_TIPO_DOCUMENTO_T_DOC FOREIGN KEY (TIPO_DOCUMENTO) REFERENCES SIGDOC.SIGDOC_TIPO_DOCUMENTO;
  ALTER TABLE SIGDOC.SIGDOC_DOCUMENTO ADD CONSTRAINT FK_ID_EXPEDIENTE_T_DOC FOREIGN KEY (ID_EXPEDIENTE) REFERENCES SIGDOC.SIGDOC_EXPEDIENTE;

--------------------------------------------------------
--  DML for Table SIGDOC_TRAZABILIDAD_EXPEDIENTE
--------------------------------------------------------


   ALTER TABLE SIGDOC.SIGDOC_TRAZABILIDAD_EXPEDIENTE ADD CONSTRAINT PK_ID_TRAZABILIDAD_EXPEDIENTE PRIMARY KEY (ID_TRAZABILIDAD_EXPEDIENTE);     
   ALTER TABLE SIGDOC.SIGDOC_TRAZABILIDAD_EXPEDIENTE ADD CONSTRAINT FK_ID_EXPEDIENTE_T_TRAZA_EXP FOREIGN KEY (ID_EXPEDIENTE) REFERENCES SIGDOC.SIGDOC_EXPEDIENTE;
   ALTER TABLE SIGDOC.SIGDOC_TRAZABILIDAD_EXPEDIENTE ADD CONSTRAINT FK_ID_ACCION_T_TRAZA_EXP FOREIGN KEY (ID_ACCION) REFERENCES SIGDOC.SIGDOC_ACCION;
   ALTER TABLE SIGDOC.SIGDOC_TRAZABILIDAD_EXPEDIENTE ADD CONSTRAINT FK_ID_ETAPA_T_TRAZA_EXP FOREIGN KEY (ID_ETAPA) REFERENCES SIGDOC.SIGDOC_ETAPA;
--------------------------------------------------------
--  DML for Table SIGDOC_NUMERACION
--------------------------------------------------------

 
   ALTER TABLE SIGDOC.SIGDOC_NUMERACION ADD CONSTRAINT PK_ID_UNIDAD PRIMARY KEY (ID_UNIDAD);     
   ALTER TABLE SIGDOC.SIGDOC_NUMERACION ADD CONSTRAINT FK_ID_TIPO_DOCUMENTO_NUMERAC FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES SIGDOC.SIGDOC_TIPO_DOCUMENTO;

