
CREATE SEQUENCE SIGDOC.SQ_ACCION;
CREATE SEQUENCE SIGDOC.SQ_CLIENTE;
CREATE SEQUENCE SIGDOC.SQ_DEPARTAMENTO;
CREATE SEQUENCE SIGDOC.SQ_DISTRITO;
CREATE SEQUENCE SIGDOC.SQ_DOCUMENTO;
CREATE SEQUENCE SIGDOC.SQ_ETAPA;
CREATE SEQUENCE SIGDOC.SQ_EXPEDIENTE;
CREATE SEQUENCE SIGDOC.SQ_NUMERACION;
CREATE SEQUENCE SIGDOC.SQ_PROCESO;
CREATE SEQUENCE SIGDOC.SQ_PROVINCIA;
CREATE SEQUENCE SIGDOC.SQ_TIPO_DOCUMENTO;
CREATE SEQUENCE SIGDOC.SQ_TIPO_IDENTIFICACION;
CREATE SEQUENCE SIGDOC.SQ_TIPO_PROCESO;
CREATE SEQUENCE SIGDOC.SQ_TRAZABILIDAD_EXPEDIENTE;
CREATE SEQUENCE SIGDOC.SQ_UNIDAD;
CREATE SEQUENCE SIGDOC.SQ_USUARIO;