REM INSERTING into SIGDOC_ETAPA
SET DEFINE OFF;
Insert into SIGDOC_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('1','RECEPCION','RECEPCION','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('2','DIGITALIACION','DIGITALIACION','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('3','DERIVACION','DERIVACION','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('4','SUSPENDIDO','SUSPENDIDO','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ETAPA (ID_ETAPA,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('5','CERRADO','CERRADO','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
