REM INSERTING into SIGDOC_ACCION
SET DEFINE OFF;
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('1','Registrar','Registrar','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('2','Reenviar','Reenviar','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('3','Devolver','Devolver','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('4','Recuperar','Recuperar','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('5','Aprobar ','Aprobar ','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('6','Aprobado','Aprobado','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_ACCION (ID_ACCION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('7','Archivar','Archivar','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
