REM INSERTING into SIGDOC_TIPO_IDENTIFICACION
SET DEFINE OFF;
Insert into SIGDOC_TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('1','RUC','Registro Unico de Contribuyente','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('2','DNI','Documento Nacional de Identidad','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('3','Otro','Otro','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('4','CE','Carnet de Extranjeria','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
