REM INSERTING into SIGDOC_TIPO_PROCESO
SET DEFINE OFF;
Insert into SIGDOC_TIPO_PROCESO (ID_TIPO_PROCESO,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('1','Flujo Documentario','Flujo Documentario','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_TIPO_PROCESO (ID_TIPO_PROCESO,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('2','Flujo Resolutivo','Flujo Resolutivo','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
Insert into SIGDOC_TIPO_PROCESO (ID_TIPO_PROCESO,NOMBRE,DESCRIPCION,ES_REGISTRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION) values ('3','Flujo Sancionador','Flujo Sancionador','1','ADM_SIGDOC',to_date('04/01/20','DD/MM/RR'),null,null);
