create or replace package SIGDOC_USUARIO_tapi
is
--CREATE SIGDOC_USUARIO
	PROCEDURE SP_CREATE_USUARIO(
		P_ID_USUARIO 		   IN SIGDOC_USUARIO.ID_USUARIO %TYPE DEFAULT NULL,
        P_ID_CLIENTE 		   IN SIGDOC_USUARIO.ID_CLIENTE%TYPE DEFAULT NULL,
		P_ID_UNIDAD 		   IN SIGDOC_USUARIO.ID_UNIDAD%TYPE,
		P_CORREO 			   IN SIGDOC_USUARIO.CORREO%TYPE DEFAULT NULL,
		P_USUARIO 			   IN SIGDOC_USUARIO.USUARIO%TYPE,
		P_CLAVE 			   IN SIGDOC_USUARIO.CLAVE%TYPE DEFAULT NULL,
        P_ES_REGISTRO          IN SIGDOC_USUARIO.FECHA_CREACION%TYPE DEFAULT NULL,
        P_FECHA_CREACION       IN SIGDOC_USUARIO.ES_REGISTRO%TYPE DEFAULT NULL,
		P_USUARIO_CREACION     IN SIGDOC_USUARIO.USUARIO_CREACION%TYPE DEFAULT NULL, 
		P_COD_RESPUESTA OUT  NUMBER,
		P_MENSAJE OUT       VARCHAR2
	);
    
-- UPDATE SIGDOC_USUARIO
	PROCEDURE SP_UPDATE_USUARIO (
		P_ID_USUARIO 		   IN SIGDOC_USUARIO.ID_USUARIO %TYPE DEFAULT NULL,
		P_ID_UNIDAD 		   IN SIGDOC_USUARIO.ID_UNIDAD%TYPE,
		P_CORREO 			   IN SIGDOC_USUARIO.CORREO%TYPE DEFAULT NULL,
		P_USUARIO 			   IN SIGDOC_USUARIO.USUARIO%TYPE,
		P_CLAVE 			   IN SIGDOC_USUARIO.CLAVE%TYPE DEFAULT NULL,
        P_FECHA_MODIFICACION       IN SIGDOC_USUARIO.FECHA_MODIFICACION%TYPE DEFAULT NULL,
		P_USUARIO_MODIFICACION     IN SIGDOC_USUARIO.USUARIO_MODIFICACION%TYPE DEFAULT NULL, 
		P_COD_RESPUESTA OUT  NUMBER,
		P_MENSAJE OUT       VARCHAR2
	);
    
-- DELETE SIGDOC_USUARIO
	PROCEDURE SP_DELETE_USUARIO(
		 p_ID_USUARIO IN SIGDOC_USUARIO.ID_USUARIO%type,
        P_ES_REGISTRO          IN SIGDOC_USUARIO.ES_REGISTRO%TYPE DEFAULT NULL,
        P_FECHA_MODIFICACION       IN SIGDOC_USUARIO.FECHA_MODIFICACION%TYPE DEFAULT NULL,
		P_USUARIO_MODIFICACION     IN SIGDOC_USUARIO.USUARIO_MODIFICACION%TYPE DEFAULT NULL,
        P_COD_RESPUESTA OUT NUMBER,
        P_MENSAJE OUT  VARCHAR2
	);
-- LEER SIGDOC_USUARIO
	PROCEDURE SP_LEER_USUARIO(
		P_USUARIO IN SIGDOC_USUARIO.USUARIO%TYPE,
        P_CURSOR OUT NOCOPY SYS_REFCURSOR,
        P_COD_RESPUESTA OUT NUMBER,
        P_MENSAJE OUT  VARCHAR2
	);/*
-- LEER LISTA SIGDOC_USUARIO
	PROCEDURE SP_LISTAR_USUARIO(
		P_CURSOR OUT NOCOPY SYS_REFCURSOR,
		P_COD_RESPUESTA OUT NOCOPY NUMBER,
		P_MENSAJE OUT NOCOPY       VARCHAR2
	);
    */
-- ENCRIPTAR	
	FUNCTION FN_ENCRIPTAR( TXT_ENCRIP VARCHAR2 ) RETURN RAW;
	
-- DESCENCRIPTAR	
	FUNCTION FN_DESCENCRIPTAR( TXT_DESENCRIP VARCHAR2 ) RETURN VARCHAR2; 
    
end SIGDOC_USUARIO_tapi;

/

