SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('INICIO PROCESO');
    
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_ACCION', 'SIGDOC_ACCION', 'ID_ACCION');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_CLIENTE', 'SIGDOC_CLIENTE', 'ID_CLIENTE');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_DEPARTAMENTO', 'SIGDOC_DEPARTAMENTO', 'ID_DEPARTAMENTO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_DISTRITO', 'SIGDOC_DISTRITO', 'ID_DISTRITO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_DOCUMENTO', 'SIGDOC_DOCUMENTO', 'ID_DOCUMENTO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_ETAPA', 'SIGDOC_ETAPA', 'ID_ETAPA');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_EXPEDIENTE', 'SIGDOC_EXPEDIENTE', 'ID_EXPEDIENTE');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_NUMERACION', 'SIGDOC_NUMERACION', 'NUMERO_ACTUAL');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_PROCESO', 'SIGDOC_PROCESO', 'ID_PROCESO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_PROVINCIA', 'SIGDOC_PROVINCIA', 'ID_PROVINCIA');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_TIPO_DOCUMENTO', 'SIGDOC_TIPO_DOCUMENTO', 'ID_TIPO_DOCUMENTO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_TIPO_IDENTIFICACION', 'SIGDOC_TIPO_IDENTIFICACION', 'ID_TIPO_IDENTIFICACION');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_TIPO_PROCESO', 'SIGDOC_TIPO_PROCESO', 'ID_TIPO_PROCESO');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_TRAZABILIDAD_EXPEDIENTE', 'SIGDOC_TRAZABILIDAD_EXPEDIENTE', 'ID_TRAZABILIDAD_EXPEDIENTE');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_UNIDAD', 'SIGDOC_UNIDAD', 'ID_UNIDAD');
    INSERT INTO CONTROL_SECUENCIAS(NOM_SECUENCIA, NOM_TABLA, COL_PK_TABLA) VALUES('SQ_USUARIO', 'SIGDOC_USUARIO', 'ID_USUARIO');
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('SE HIZO COMMIT');
    DBMS_OUTPUT.PUT_LINE('FIN DE PROCESO');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(chr(10) || '********** ERROR AL EJECUTAR EL BLOQUE **********');
        DBMS_OUTPUT.PUT_LINE('CODERROR [' || SQLCODE || ']');
        DBMS_OUTPUT.PUT_LINE('MSGERROR [' || SQLERRM || ']');
        DBMS_OUTPUT.PUT_LINE('LINEA ERROR [' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ']');
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('********** SE HIZO ROLLBACK **********');
END;
/
