
-- BUCLE WHILE

DECLARE 
  CURSOR C_DEMO IS 
    SELECT * FROM SCOTT.EMP;
  V_REG SCOTT.EMP%ROWTYPE;
BEGIN
  OPEN C_DEMO;
  
  FETCH C_DEMO INTO V_REG;
  WHILE C_DEMO%FOUND LOOP
    dbms_output.put_line( V_REG.EMPNO || ' - ' || V_REG.ENAME || ' - ' || V_REG.SAL);
    FETCH C_DEMO INTO V_REG;
  END LOOP;
  
  CLOSE C_DEMO;
END;
/

