/*-------------------- CREACIÓN DE USUARIO MUSIC GALAXY (MG) --------------------*/
-- 1. ELIMINAR USUARIO EN CASO EXISTA
DECLARE
	X INT;
	COMANDO VARCHAR2(200);
BEGIN
	COMANDO := 'DROP USER MG CASCADE';
	
    SELECT  COUNT(*) 
    INTO    X
	FROM    DBA_USERS
	WHERE   USERNAME = 'MG';
    
	IF (X = 1) THEN
		EXECUTE IMMEDIATE COMANDO;
	END IF;
END;
/
-- 2. CREAR EL USUARIO Y LA CONTRASEÑA
-- alter session set "_ORACLE_SCRIPT"=true; -- Por si no permite crear al usuario
CREATE USER MG IDENTIFIED BY musica;

-- 3. DAR PERMISOS AL USUARIO
GRANT CONNECT, RESOURCE TO MG;
GRANT CREATE VIEW TO MG;
GRANT CREATE TABLE TO MG;
GRANT UNLIMITED TABLESPACE TO MG;
