/*-------------------- POBLACIÓN DE DATOS INICIAL --------------------*/

-- TABLA CALENDARIO
DECLARE 
        FECHA_IN DATE;
        FECHA_FIN DATE;
BEGIN
        FECHA_IN := TO_DATE('20040101','YYYYMMDD');
        FECHA_FIN := TO_DATE((TO_CHAR(SYSDATE,'YYYY') || '1231'),'YYYYMMDD');

        WHILE FECHA_IN != FECHA_FIN LOOP
                INSERT INTO MG.T_CALENDARIO 
                (
                FECHASK,
                FECHA,
                ANIO,
                TRIMESTRE,
                MES,
                SEMANA,
                DIA,
                NMES,
                NDIASEMANA
                )
                VALUES
                (
                TO_CHAR(FECHA_IN,'DDMMYYYY'),
                FECHA_IN,
                TO_CHAR(FECHA_IN,'YYYY'),
                TO_CHAR(FECHA_IN,'Q'),
                TO_CHAR(FECHA_IN,'MM'),
                TO_CHAR(FECHA_IN,'WW'),
                TO_CHAR(FECHA_IN,'DD'),
                TO_CHAR(FECHA_IN,'MONTH'),
                TO_CHAR(FECHA_IN,'DAY')
                );
                
                FECHA_IN := FECHA_IN + 1;
        END LOOP;
END;
/

-- TABLA PAIS
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'PERU');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'ARGENTINA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'CHILE');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'COLOMBIA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'BOLIVIA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'BRASIL');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'ECUADOR');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'URUGUAY');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'PARAGUAY');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'MEXICO');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'USA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'CANADA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'FRANCIA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'ALEMANIA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'ESPAÑA');
INSERT INTO MG.T_PAIS(ID_PAIS,PAIS) VALUES(MG.SEQ_PAIS_ID.NEXTVAL,'VENEZUELA');

-- TABLA GENERO
INSERT INTO MG.T_GENERO(ID_GENERO,GENERO) VALUES(MG.SEQ_GENERO_ID.NEXTVAL,'MASCULINO');
INSERT INTO MG.T_GENERO(ID_GENERO,GENERO) VALUES(MG.SEQ_GENERO_ID.NEXTVAL,'FEMENINO');
/
-- TABLA PERSONA
DECLARE X NUMBER;
BEGIN
        FOR X IN 1..3000 LOOP
            INSERT INTO MG.T_PERSONA(ID_PERSONA,ID_PAIS,ID_GENERO,NOMBRES,FECHA_NAC,FLAG) 
                VALUES (MG.SEQ_PERSONA_ID.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,16)),TRUNC(DBMS_RANDOM.VALUE(1,3)),'ANONIMO ' || X,TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '1980-01-01','J'),TO_CHAR(DATE '1999-12-31','J'))),'J'),1);
        END LOOP;
END;
/
-- TABLA TIPOS DE USUARIO
INSERT INTO MG.T_TIPO_USUARIO(ID_TIPO_USUARIO,TIPO_USUARIO,LIMITE) VALUES(MG.SEQ_TIPO_USUARIO_ID.NEXTVAL,'FREE',2);
INSERT INTO MG.T_TIPO_USUARIO(ID_TIPO_USUARIO,TIPO_USUARIO) VALUES(MG.SEQ_TIPO_USUARIO_ID.NEXTVAL,'PREMIUM');
/
-- TABLA USUARIOS
DECLARE X NUMBER;
BEGIN
        FOR X IN 1..3000 LOOP
            INSERT INTO MG.T_USUARIO(ID_USUARIO,ID_TIPO_USUARIO,ID_PERSONA,USUARIO,CONTRASENIA,FLAG,FECHA_REG,FECHA_BAJA) 
            VALUES(MG.SEQ_USUARIO_ID.NEXTVAL,1,X,'anonimo' || X,'123456',1,TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2015-01-01','J'),TO_CHAR(DATE '2020-03-09','J'))),'J'),NULL);
        END LOOP;
END;
/
-- TABLA ARTISTAS
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'GIAN MARCO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'PEDRO SUAREZ VERTIZ');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'SHAKIRA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'MICHAEL JACKSON');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'LIBIDO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'MAR DE COPAS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'BEYONCE');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,2,'ENANITOS VERDES');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,10,'JOSE JOSE');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'CAMILO SESTO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,10,'JUAN GABRIEL');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'ENRIQUE IGLESIAS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'PITBULL');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'JUSTIN BIEBER');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'RIHANNA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'MILEY CIRUS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'JLO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'KATY PERRY');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'MADONNA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'RICKY MARTIN');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'MARC ANTHONY');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,10,'LUIS MIGUEL');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'PINK');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'USHER');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,11,'KISS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,10,'PEDRO INFANTE');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'JULIO IGLESIAS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'MIGUEL BOSE');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'CARLOS VIVES');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'JUANES');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'FONSECA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,16,'RICARDO MONTANER');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,16,'FRANCO DE VITA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,16,'NACHO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,10,'VICENTE FERNANDEZ');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'DAVID BISBAL');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,15,'ROSALIA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'AMEN');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'LOS MOJARRAS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'CHABELOS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'RAUL ROMERO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,1,'ZEN');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,2,'SODA STEREO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,2,'RATA BLANCA');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,3,'LOS PRISIONEROS');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,3,'LA LEY');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'DIOMEDES DIAZ');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'BINOMIO DE ORO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'GIGANTES DEL VALLENATO');
INSERT INTO MG.T_ARTISTA(ID_ARTISTA,ID_PAIS,ARTISTA) VALUES(MG.SEQ_ARTISTA_ID.NEXTVAL,4,'LOS DIABLITOS');

-- TABLA CANCIONES
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'TU NO TE IMAGINAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'SENTIRME VIVO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'SACALA A BAILAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'TE MENTIRIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'EMPECEMOS A VIVIR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'NO PUEDO AMARTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'CANTA CORAZON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,1,'LEJOS DE TI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'CUANDO PIENSES EN VOLVER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'LOS GLOBOS DEL CIELO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'COMO LAS MARIPOSAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'CUENTAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'LO OLVIDE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'ME ESTOY ENAMORANDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'NO PENSE QUE ERA AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'DEGENERACION ACTUAL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'MI AUTO ERA UNA RANA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'SI ESCUCHAS UN ANGEL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'ALGUIEN QUE BESE COMO TU');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,2,'NO LLORES MAS MORENA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'WAKA WAKA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'CHANTAJE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'ANTOLOGIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'INEVITABLE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'LA TORTURA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'LA LA LA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'SHE WOLF');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'OJOS ASI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'LA BICICLETA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'PERRO FIEL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'CIEGA, SORDOMUDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'CLANDESTINO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'LOCA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'RABIOSA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,3,'NO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'BEAT IT');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'BILLIE JEAN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'BLACK OR WHITE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'DIRTY DIANA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'DO NOT STOP TILL YOU GET ENOUGH');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'EARTH SONG');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'GHOSTS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'IN THE CLOSET');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'MONEY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'SMOOTH CRIMINAL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'SPEED DEMON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,4,'WHO IS IT');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,5,'NO VOY A VERTE MAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,5,'SED');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,5,'SIN RENCOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,5,'MALVADA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,6,'UN DIA SIN SEXO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,6,'MUJER NOCHE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,6,'LLEVAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,6,'ADIOS AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,6,'DULCE Y VELOZ');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'HALO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'CRAZY IN LOVE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'SINGLE LADIES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'LOVE ON TOP');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'HOLD UP');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,7,'MUJER NOCHE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'LAMENTO BOLIVIANO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'LUZ DE DIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'TU CARCEL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'LA MURALLA VERDE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'IGUAL QUE AYER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,8,'TUS VIEJAS CARTAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'EL TRISTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'EL AMAR Y EL QUERER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'ALMOHADA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'HE RENUNCIADO A TI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'LO PASADO, PASADO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'LO QUE NO FUE NO SERA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'SERA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'40 Y 20');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'PIEL DE AZUCAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,9,'DESESPERADO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'PERDONAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'EL AMOR DE MI VIDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'MELINA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'¿QUIERES SER MI AMANTE?');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'VIVIR ASI ES MORIR DE AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'ALGO DE MI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'JAMAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'PIEL DE ANGEL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,10,'VIVIR SIN TI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'ASI FUE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'HASTA QUE TE CONOCI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'ABRAZAME MUY FUERTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'AMOR ETERNO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'EL NOA NOA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'SI QUIERES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'YO NO NACI PARA AMAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'QUERIDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'TE SIGO AMANDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,11,'NO TENGO DINERO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'BAILANDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'EL PERDEDOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'SUBEME LA RADIO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'CUANDO ME ENAMORO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'EL PERDON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'NUNCA TE OLVIDARE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'LOCO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,12,'DUELE EL CORAZON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'TIMBER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'WE ARE ONE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'GIVE ME EVERYTHING');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'FEEL THIS MOMENT');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'FIREBALL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,13,'COMO YO LE DOY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,14,'SORRY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,14,'YUMMY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,14,'LOVE YOURSELF');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,14,'WHAT DO YOU MEAN?');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,14,'BABY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'DIAMONDS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'UMBRELLA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'WE FOUND LOVE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'STAY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'WORK');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'ONLY GIRL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,15,'RUDE BOY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,16,'WRECKING BALL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,16,'THE CLIMB');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,16,'WHE CANT STOP');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,16,'MALIBU');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,17,'ON THE FLOOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,17,'DANCE AGAIN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,17,'EL ANILLO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,17,'GET RIGHT');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,17,'DINERO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'ROAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'DARK HORSE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'FIREWORK');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'HOT N COLD');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'SWISH SWISH');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,18,'E.T');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,19,'LA ISLA BONITA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,19,'VOGUE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,19,'LIKE A VIRGIN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'LA VIDA LOCA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'LA MORDIDITA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'MARIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'VENTE PA CA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'PEGATE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,20,'VUELVE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'VIVIR MI VIDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'DIMELO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'CAMBIO DE PIEL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'VALIO LA PENA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'Y COMO ES EL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'A QUIEN QUIERO MENTIRLE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,21,'VIVIR LO NUESTRO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,22,'LA INCONDICIONAL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,22,'TENGO TODO EXCEPTO A TI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,22,'CUPABLE O NO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,22,'POR DEBAJO DE LA MESA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'JUST GIVE ME A REASON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'TRY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'WHAT ABOUT US');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'LADY MARMALADE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'SO WHAT');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'WALK ME HOME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,23,'BLOW ME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,24,'BURN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,24,'WITHOUT YOU');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,25,'I WAS MADE FOR LOVIN YOU');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,26,'FALLASTE CORAZON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,26,'LAS MAÑANITAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,26,'ENTRE COPA Y COPA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,27,'ME OLVIDE DE VIVIR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,27,'ABRAZAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,27,'BAILA MORENA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,27,'LA VIDA SIGUE IGUAL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,28,'AMANTE BANDIDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,28,'AMIGA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,28,'DON DIABLO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'ROBARTE UN BESO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'NOTA DE AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'UN POQUITO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'AY DIOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'LA TIERRA DEL OLVIDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'VOLVI A NACER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,29,'CARITO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'BESOS EN GUERRA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'A DIOS LE PIDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'ES POR TI ');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'PARA TU AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'ME ENAMORA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'NADA VALGO SIN TU AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,30,'ES TARDE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'ERES MI SUEÑO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'ARROYITO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'TE MANDO FLORES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'VOLVER A VERTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'VINE A BUSCARTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'SIMPLES CORAZONES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'VEN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'SI TE ACUERDAS DE MI');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,31,'ENREDAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,32,'LA GLORIA DE DIOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,32,'TE ADORARE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,32,'ME VA EXTRAÑAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,32,'TE HUBIERAS IDO ANTES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,32,'SOLO CON UN BESO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'TE AMO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'TU DE QUE VAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'SI LA VES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'NO BASTA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'UN BUEN PERDEDOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,33,'Y TE PIENSO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,34,'HAPPY HAPPY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,34,'TE QUIERO MAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,34,'DEJALO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,34,'MI VIDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,35,'A MI MANERA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,35,'ESTOS CELOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,35,'A PESAR DE TODO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,35,'SUBLIME MUJER');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,35,'AMOR DE LOS DOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'DIGALE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'MUCHO MAS ALLA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'A PARTIR DE HOY');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'MI PRINCESA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'PERDON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,36,'BULERIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,37,'CON ALTURA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'DECIR ADIOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'FIN DEL TIEMPO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'LA CHATA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'TE QUIERO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'SE QUE TU NO ESTAS SOLO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,38,'ENTRE TUS LLAMAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,39,'TRICICLO PERU');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,39,'CACHUCA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,40,'SHAKIRA Y SUS AMIGAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,40,'EL QUINTO TELETUBIE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,40,'LOCO POR TU AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,40,'LUISA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,41,'LAS TORRES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,41,'MAGDALENA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,41,'NO NECESITO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,42,'VUELVE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,42,'MIENTEME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,42,'UN DIA MAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'DE MUSICA LIGERA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'EN LA CIUDAD DE LA FURIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'PERSIANA AMERICANA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'CUANDO PASE EL TEMBLOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'PROFUGOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'SIGNOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,43,'NADA PERSONAL');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,44,'MUJER AMANTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,44,'AUN ESTAS EN MIS SUEÑOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,44,'EL SUEÑO DE LA GITANA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,44,'ELLA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,45,'ESTRECHEZ DE CORAZON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,45,'PORQUE NO SE VAN');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,45,'SEXO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,45,'TREN AL SUR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,46,'MENTIRA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,46,'DIA CERO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,46,'EL DUELO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'LA SUERTE ESTA ECHADA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'SIN MEDIR DISTANCIAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'AMARTE MAS NO PUDE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'MI PRIMERA CAMA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'ILUSIONES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,47,'TU CUMPLEAÑOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'SI TU AMOR NO VUELVE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'COMO TE OLVIDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'UN OSITO DORMILON');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'ME VAS A EXTRAÑAR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'NIÑA BONITA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'ME ILUSIONE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'HOY ME DI CUENTA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,48,'VOLVIO EL DOLOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'NO HE PODIDO SER FELIZ');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'ME MATA LA MELANCOLIA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'PERDONAME');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'ACUERDATE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'QUE DESCARO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'COMO TE ATREVES');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,49,'ENTRE AMIGOS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'NO TE VAYAS');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'LOS CAMINOS DE LA VIDA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'BUSCA UN CONFIDENTE');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'DEJALA');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'SUEÑOS DE OLVIDO');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'RECUERDOS DE UN AMOR');
INSERT INTO MG.T_CANCION(ID_CANCION,ID_ARTISTA,CANCION) VALUES(MG.SEQ_CANCION_ID.NEXTVAL,50,'A BESITOS');
/

-- TABLA DE CANCIONES REPRODUCIDAS
DECLARE X NUMBER;
BEGIN
        FOR X IN 1..100000 LOOP 
            INSERT INTO MG.T_CANCION_REPRO(ID_CANCION_REPRO,ID_USUARIO,ID_CANCION,FECHA) VALUES(MG.SEQ_CANCION_REPRO_ID.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,3001)),TRUNC(DBMS_RANDOM.VALUE(1,293)),TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2015-01-01','J'),TO_CHAR(DATE '2020-03-09','J'))),'J'));        
        END LOOP;
END;
/
-- LISTA DE REPRODUCCION
INSERT INTO MG.T_LISTA_REPROD(ID_LISTA_REPROD,ID_USUARIO,LISTA_REPRODUCCION) VALUES(MG.SEQ_LISTA_REPROD_ID.NEXTVAL,1,'ANTIGUAS');
INSERT INTO MG.T_LISTA_REPROD(ID_LISTA_REPROD,ID_USUARIO,LISTA_REPRODUCCION) VALUES(MG.SEQ_LISTA_REPROD_ID.NEXTVAL,2,'80s');

COMMIT;


