
CREATE OR REPLACE PROCEDURE SCOTT.SP_DIVISION 
(DIVIDENDO IN NUMBER, DIVISOR IN NUMBER, COCIENTE OUT NUMBER, RESIDUO OUT NUMBER)
IS
    VAR_DIVIDENDO NUMBER := DIVIDENDO;
    VAR_COCIENTE NUMBER := 0;
BEGIN
    WHILE (VAR_DIVIDENDO >= DIVISOR) LOOP
        VAR_DIVIDENDO := VAR_DIVIDENDO - DIVISOR;
        VAR_COCIENTE := VAR_COCIENTE + 1;
    END LOOP;
    
    COCIENTE := VAR_COCIENTE;
    RESIDUO := VAR_DIVIDENDO;
END;
/

VAR COCIENTE NUMBER;
VAR RESIDUO NUMBER;
EXECUTE SCOTT.SP_DIVISION(5,2,:COCIENTE,:RESIDUO);
PRINT COCIENTE;
PRINT RESIDUO;


VAR COCIENTE NUMBER;
VAR RESIDUO NUMBER;
EXECUTE SCOTT.SP_DIVISION(3989,1247,:COCIENTE,:RESIDUO);
PRINT COCIENTE;
PRINT RESIDUO;
