CREATE OR REPLACE FUNCTION 
SCOTT.FN_MAYOR_NUM (P_N1 NUMBER, P_N2 NUMBER, P_N3 NUMBER, P_N4 NUMBER, P_N5 NUMBER)
RETURN NUMBER
IS
    V_MAYOR NUMBER;
BEGIN
    
    V_MAYOR := P_N1;
    
    IF (P_N2 > V_MAYOR) THEN
        V_MAYOR := P_N2;
    END IF;
    IF (P_N3 > V_MAYOR) THEN
        V_MAYOR := P_N3;
    END IF;
    IF (P_N4 > V_MAYOR) THEN
        V_MAYOR := P_N4;
    END IF;
    IF (P_N5 > V_MAYOR) THEN
        V_MAYOR := P_N5;
    END IF;
    
    RETURN V_MAYOR;
END;
/


VAR MAXIMO NUMBER;
EXEC :MAXIMO:= SCOTT.FN_MAYOR_NUM(-10,-2,-5,-1,-8)
PRINT MAXIMO


