CREATE OR REPLACE FUNCTION SCOTT.FN_NUM_PRIMO(N NUMBER)
RETURN VARCHAR2
IS
    RESULT VARCHAR2(20);
    N_ABS NUMBER := ABS(N);
    CONT NUMBER := 0;
BEGIN
    FOR I IN 1..N_ABS LOOP
        IF (MOD(N_ABS,I) = 0) THEN
            CONT := CONT + 1;
        END IF;
    END LOOP;
    
    IF (CONT > 2) THEN
        RESULT := 'NO ES PRIMO';
    ELSE
        RESULT := 'ES PRIMO';
    END IF;
    
    RETURN RESULT;
END;
/

SELECT  SCOTT.FN_NUM_PRIMO(50) FROM DUAL;



